### ISSUE TITLE
mechanical engineering

### ISSUE THREAD

**Issue by ghost** [codetechandtutorials/OurLordAndSavior#3]
_This is a response to one of the videos which falsesly uses the respected word "Engineering" in it._
Hey
@mattearly  just wanted to say that  Engineering has nothing to do with sitting behind a keyboard and writing code. Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs are claiming the most ridiculous of false claims these days. Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering.

Mechanical Engineering is the only Engineering.

bye bye

**Comment by mattearly** [comment]
wut
